server:
  port: 8090

spring:
  datasource:
    name: springboot-mybatis-generator-cache-demo
    url: jdbc:mysql://172.12.0.3:3306/springboot_mybaties_generator_demo
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filter:
        wall:
          config:
            multi-statement-allow: true
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 5000
          db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.12.0.3:3306/springboot_mybaties_generator_demo
      username: root
      password: root



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.mybatis.generator.demo.pojo  # 注意：对应实体类的路径


#showSql
logging:
  level:
    com:
      example:
        mybatis:
          generator:
            demo:
              dao: DEBUG

    com.neo.mapper: DEBUG